# Copyright (c) 2025 JP Hutchins
# SPDX-License-Identifier: MIT

"""
Test that generates LaTeX examples documentation.

This test generates the latex_examples.md file by executing actual Python code
and capturing the LaTeX output. This ensures the documentation stays in sync
with the implementation.
"""

from pathlib import Path
from typing import Any, NamedTuple, cast

from mahonia import (
	Approximately,
	Const,
	Expr,
	Percent,
	PlusMinus,
	Predicate,
	Var,
)
from mahonia.latex import LatexCtx, Show, latex


def test_generate_latex_examples() -> None:
	"""Generate the LaTeX examples markdown file."""

	# Define context for examples
	class Ctx(NamedTuple):
		x: float
		y: float
		z: float
		w: float
		a: float
		b: float
		c: float
		v: float

	# Start building the markdown content
	lines = [
		"# LaTeX Examples from Mahonia",
		"",
		"This document demonstrates the LaTeX output generated by the `mahonia.latex` module for various mathematical expressions.",
		"",
		"> [!IMPORTANT]",
		"> This file is auto-generated by `tests/test_latex_examples.py`",
		"> Do not edit this file directly. Run the test to regenerate.",
		"",
		"## Setup",
		"",
		"All examples use the following setup:",
		"",
		"```python",
		"from typing import NamedTuple",
		"from mahonia import Var, Const, PlusMinus, Percent, Approximately, Predicate",
		"from mahonia.latex import latex",
		"",
		"class Ctx(NamedTuple):",
		"    x: float",
		"    y: float",
		"    # ... other fields as needed",
		"```",
		"",
		"## Basic Variables",
		"",
		"### Simple Variables",
	]

	# Basic variables
	x = Var[int, Ctx]("x")
	y = Var[int, Ctx]("y")
	lines.extend(
		[
			f"- Variable `x`: `latex(Var[int, Ctx]('x'))` → ${latex(x)}$",
			f"- Variable `y`: `latex(Var[int, Ctx]('y'))` → ${latex(y)}$",
			"",
		]
	)

	# Subscripts
	lines.extend(
		[
			"### Variables with Subscripts",
			"",
		]
	)

	x1 = Var[int, Ctx]("x_1")
	x_max = Var[int, Ctx]("x_max")
	velocity_initial = Var[float, Ctx]("velocity_initial")

	lines.extend(
		[
			f"- Single character subscript: `latex(Var('x_1'))` → ${latex(x1)}$",
			f"- Multiple character subscript: `latex(Var('x_max'))` → ${latex(x_max)}$",
			f"- Complex subscript: `latex(Var('velocity_initial'))` → ${latex(velocity_initial)}$",
			"",
		]
	)

	# Greek letters
	lines.extend(
		[
			"### Greek Letter Variables",
			"",
		]
	)

	greek_vars = [
		("alpha", "α"),
		("beta", "β"),
		("gamma", "γ"),
		("delta", "δ"),
		("epsilon", "ε"),
		("theta", "θ"),
		("pi", "π"),
		("sigma", "σ"),
		("omega", "ω"),
	]

	for name, _symbol in greek_vars:
		var = Var[float, Ctx](name)
		lines.append(f"- {name.capitalize()}: `latex(Var('{name}'))` → ${latex(var)}$")
	lines.extend(["", ""])

	# Constants
	lines.extend(
		[
			"## Constants",
			"",
			"### Numeric Constants",
			"",
		]
	)

	const_examples = [
		(Const(None, 42), "Const(None, 42)", "Integer"),
		(Const(None, 3.14159), "Const(None, 3.14159)", "Float"),
		(Const(None, -5), "Const(None, -5)", "Negative"),
	]

	for const, code, desc in const_examples:
		lines.append(f"- {desc}: `latex({code})` → ${latex(cast(Expr[Any, Any], const))}$")
	lines.extend(["", ""])

	# Named constants
	lines.extend(
		[
			"### Named Constants",
			"",
		]
	)

	pi_const = Const("Pi", 3.14159)  # This becomes \pi due to Greek letter conversion
	zero_const = Const("Zero", 0)

	named_examples = [
		(pi_const, "Const('Pi', 3.14159)", "Named constant Pi (becomes Greek π)"),
		(zero_const, "Const('Zero', 0)", "Zero constant"),
	]

	for const, code, desc in named_examples:
		lines.append(f"- {desc}: `latex({code})` → ${latex(cast(Expr[Any, Any], const))}$")
	lines.extend(["", ""])

	# Arithmetic Operations
	lines.extend(
		[
			"## Arithmetic Operations",
			"",
			"### Basic Operations",
			"",
		]
	)

	x_float = Var[float, Ctx]("x")
	y_float = Var[float, Ctx]("y")

	lines.extend(
		[
			f"- Addition: `latex(x + y)` → ${latex(x + y)}$",
			f"- Subtraction: `latex(x - y)` → ${latex(x - y)}$",
			f"- Multiplication: `latex(x * y)` → ${latex(x_float * y_float)}$",
			f"- Division: `latex(x / y)` → ${latex(x_float / y_float)}$",
			"",
		]
	)

	# Power Operations
	lines.extend(
		[
			"### Power Operations",
			"",
			f"- Square: `latex(x ** 2)` → ${latex(x**2)}$",
			f"- Variable exponent: `latex(x ** y)` → ${latex(x**y)}$",
			f"- Complex exponent: `latex(x ** (y + 1))` → ${latex(x ** (y + 1))}$",
			f"- Base with parentheses: `latex((x + y) ** 2)` → ${latex((x + y) ** 2)}$",
			"",
		]
	)

	# Complex Arithmetic
	lines.extend(
		[
			"### Complex Arithmetic",
			"",
		]
	)

	z_float = Var[float, Ctx]("z")
	complex_examples = [
		(
			((x_float + y_float) * z_float) / (x_float - y_float),
			"((x + y) * z) / (x - y)",
			"Nested expression",
		),
		(
			x_float**3 + Const("Two", 2) * x_float**2 - x_float + Const("One", 1),
			"x**3 + 2*x**2 - x + 1",
			"Polynomial",
		),
	]

	for expr, code, desc in complex_examples:
		if "polynomial" in desc.lower():
			lines.extend(
				[
					"```python",
					"x = Var[float, Ctx]('x')",
					"two = Const('Two', 2)",
					"one = Const('One', 1)",
					"expr = x**3 + two*x**2 - x + one",
					f"latex(expr)  # '{latex(cast(Expr[Any, Any], expr))}'",
					"```",
				]
			)
		else:
			lines.extend(
				[
					"```python",
					"x = Var[float, Ctx]('x')",
					"y = Var[float, Ctx]('y')",
					"z = Var[float, Ctx]('z')",
					f"expr = {code}",
					f"latex(expr)  # '{latex(cast(Expr[Any, Any], expr))}'",
					"```",
				]
			)
		lines.extend(
			[
				f"- {desc}: ${latex(cast(Expr[Any, Any], expr))}$",
				"",
			]
		)

	# Comparison Operations
	lines.extend(
		[
			"## Comparison Operations",
			"",
			"### Basic Comparisons",
			"",
			f"- Equal `latex(x == y)`: ${latex(x == y)}$",
			f"- Not equal `latex(x != y)`: ${latex(x != y)}$",
			f"- Less than `latex(x < y)`: ${latex(x < y)}$",
			f"- Less than or equal `latex(x <= y)`: ${latex(x <= y)}$",
			f"- Greater than `latex(x > y)`: ${latex(x > y)}$",
			f"- Greater than or equal `latex(x >= y)`: ${latex(x >= y)}$",
			"",
			"### Complex Comparisons",
			"",
			f"- With arithmetic `latex((x + 5) > (y * 2))`: ${latex((x + 5) > (y * 2))}$",
			"",
		]
	)

	# Logical Operations
	lines.extend(
		[
			"## Logical Operations",
			"",
			"### Basic Logic",
			"",
			f"- AND `latex((x > 5) & (y < 10))`: ${latex((x > 5) & (y < 10))}$",
			f"- OR `latex((x > 5) | (y < 10))`: ${latex((x > 5) | (y < 10))}$",
			f"- NOT `latex(~(x > 5))`: ${latex(~(x > 5))}$",
			"",
			"### Complex Logic",
			"",
			f"- Nested NOT: ${latex(~((x > 5) & (y < 10)))}$",
			f"- Mixed operations: ${latex(((x_float + y_float) > 10) & ((x_float * y_float) < 50) | (x_float / y_float > 2))}$",
			"",
		]
	)

	# Special Expressions
	pm1 = PlusMinus("measurement", 5.0, 0.1)
	pm2 = PlusMinus(None, 5.0, 0.1)
	pct1 = Percent("measurement", 5.0, 2.0)
	pct2 = Percent(None, 5.0, 2.0)

	x_approx = Var[float, Ctx]("x")
	target1 = PlusMinus("target", 5.0, 0.1)
	target2 = PlusMinus("target2", 10.0, 0.2)
	approx1 = Approximately(x_approx, target1)
	approx2 = Approximately(x_approx ** Const(None, 2.0), target2)

	pred1 = Predicate("condition", x > 5)
	pred2 = Predicate(None, x > 5)

	lines.extend(
		[
			"## Special Expressions",
			"",
			"### Plus-Minus Expressions",
			"",
			f"- Named measurement: ${latex(pm1)}$",
			f"- Unnamed measurement: ${latex(pm2)}$",
			"",
			"### Percentage Expressions",
			"",
			f"- Named percentage: ${latex(pct1)}$",
			f"- Unnamed percentage: ${latex(pct2)}$",
			"",
			"### Approximately Expressions",
			"",
			f"- Basic approximation: ${latex(approx1)}$",
			f"- Complex approximation: ${latex(approx2)}$",
			"",
			"### Predicate Expressions",
			"",
			f"- Named predicate: ${latex(pred1)}$",
			f"- Unnamed predicate: ${latex(pred2)}$",
			"",
		]
	)

	# Real-World Examples
	a = Var[float, Ctx]("a")
	b = Var[float, Ctx]("b")
	c = Var[float, Ctx]("c")
	discriminant = b**2 - Const("Four", 4) * a * c

	m = Var[float, Ctx]("m")
	v = Var[float, Ctx]("v")
	F = Var[float, Ctx]("F")
	half = Const(None, 0.5)
	kinetic_energy = half * m * v**2
	force_eq = F == m * a

	V = Var[float, Ctx]("V")
	voltage_spec = Approximately(V, PlusMinus(None, 5.0, 0.1))
	resistance_tol = Percent("R", 100.0, 5.0)
	T = Var[float, Ctx]("T")
	temp_range = (Const(None, 20) <= T) & (T <= Const(None, 25))

	lines.extend(
		[
			"## Real-World Examples",
			"",
			"### Quadratic Formula Components",
			"",
			f"- Discriminant `b² - 4ac`: ${latex(discriminant)}$",
			"",
			"### Physics Equations",
			"",
			f"- Kinetic energy: ${latex(kinetic_energy)}$",
			f"- Force equation: ${latex(force_eq)}$",
			"",
			"### Engineering Tolerances",
			"",
			f"- Voltage specification: ${latex(voltage_spec)}$",
			f"- Resistance tolerance: ${latex(resistance_tol)}$",
			f"- Temperature range: ${latex(temp_range)}$",
			"",
		]
	)

	# Parentheses Logic Examples
	z_int = Var[int, Ctx]("z")

	lines.extend(
		[
			"## Parentheses Logic Examples",
			"",
			"### Precedence Demonstrations",
			"",
			f"- Multiplication precedence `latex(x + y * z)`: ${latex(x + y * z_int)}$",
			f"- Addition needs parentheses `latex((x + y) * z)`: ${latex((x + y) * z_int)}$",
			f"- Subtraction on right `latex(x - (y + z))`: ${latex(x - (y + z_int))}$",
			f"- Division complexity `latex(x / (y * z))`: ${latex(x_float / (y_float * z_float))}$",
			"",
		]
	)

	# Edge Cases
	zero = Const(None, 0)
	one = Const(None, 1)
	neg_five = Const(None, -5)

	lines.extend(
		[
			"## Edge Cases",
			"",
			"### Special Values",
			"",
			f"- Zero operations `latex(x + 0)`: ${latex(x + zero)}$",
			f"- Negative constants `latex(x + (-5))`: ${latex(x + neg_five)}$",
			f"- Identity operations `latex(x * 1)`: ${latex(x * one)}$",
			"",
		]
	)

	# Context Examples - NEW SECTION
	# Define a concrete context for examples
	ctx = Ctx(x=2.0, y=3.0, z=1.5, w=4.0, a=1.0, b=2.0, c=3.0, v=5.0)

	lines.extend(
		[
			"## Expressions with Context",
			"",
			"The `latex()` function supports an optional context parameter that evaluates variables and shows their values:",
			"",
			"```python",
			"# Define context with concrete values",
			"ctx = Ctx(x=2.0, y=3.0, z=1.5, w=4.0)",
			"",
			"# Without context - shows expression structure",
			"latex(expr)  # Shows symbolic form",
			"",
			"# With context - shows values",
			"latex(expr, ctx)  # Shows evaluated values",
			"```",
			"",
		]
	)

	# Context examples for variables
	x_ctx = Var[float, Ctx]("x")
	y_ctx = Var[float, Ctx]("y")
	z_ctx = Var[float, Ctx]("z")

	lines.extend(
		[
			"### Variables with Context",
			"",
			f"- Variable without context: `latex(x)` → ${latex(x_ctx)}$",
			f"- Variable with context: `latex(x, LatexCtx(ctx))` → ${latex(x_ctx, LatexCtx(ctx))}$",
			"",
		]
	)

	# Context examples for arithmetic
	lines.extend(
		[
			"### Arithmetic with Context",
			"",
		]
	)

	add_ctx = x_ctx + y_ctx
	mul_ctx = x_ctx * y_ctx
	div_ctx = x_ctx / y_ctx
	pow_ctx = x_ctx**2

	lines.extend(
		[
			f"- Addition: `latex(x + y)` → ${latex(add_ctx)}$",
			f"- Addition with context: `latex(x + y, ctx)` → ${latex(add_ctx, LatexCtx(ctx))}$",
			"",
			f"- Multiplication: `latex(x * y)` → ${latex(mul_ctx)}$",
			f"- Multiplication with context: `latex(x * y, ctx)` → ${latex(mul_ctx, LatexCtx(ctx))}$",
			"",
			f"- Division: `latex(x / y)` → ${latex(div_ctx)}$",
			f"- Division with context: `latex(x / y, ctx)` → ${latex(div_ctx, LatexCtx(ctx))}$",
			"",
			f"- Power: `latex(x ** 2)` → ${latex(pow_ctx)}$",
			f"- Power with context: `latex(x ** 2, ctx)` → ${latex(pow_ctx, LatexCtx(ctx))}$",
			"",
		]
	)

	# Context examples for comparisons and logic
	lines.extend(
		[
			"### Comparisons with Context",
			"",
		]
	)

	lt_ctx = x_ctx < y_ctx
	eq_ctx = x_ctx == 2.0
	complex_logic = (x_ctx > 1.0) & (y_ctx < 5.0)

	lines.extend(
		[
			f"- Less than: `latex(x < y)` → ${latex(lt_ctx)}$",
			f"- Less than with context: `latex(x < y, ctx)` → ${latex(lt_ctx, LatexCtx(ctx))}$",
			"",
			f"- Equality: `latex(x == 2.0)` → ${latex(eq_ctx)}$",
			f"- Equality with context: `latex(x == 2.0, ctx)` → ${latex(eq_ctx, LatexCtx(ctx))}$",
			"",
			f"- Complex logic: `latex((x > 1.0) & (y < 5.0))` → ${latex(complex_logic)}$",
			f"- Complex logic with context: `latex((x > 1.0) & (y < 5.0), ctx)` → ${latex(complex_logic, LatexCtx(ctx))}$",
			"",
		]
	)

	# Context examples for special expressions
	lines.extend(
		[
			"### Special Expressions with Context",
			"",
		]
	)

	approx_ctx = Approximately(x_ctx, PlusMinus("target", 2.0, 0.1))
	pred_ctx = Predicate("condition", x_ctx > 1.5)

	lines.extend(
		[
			f"- Approximately: `latex(x ≈ target ± 0.1)` → ${latex(approx_ctx)}$",
			f"- Approximately with context: `latex(x ≈ target ± 0.1, ctx)` → ${latex(approx_ctx, LatexCtx(ctx))}$",
			"",
			f"- Predicate: `latex(condition: x > 1.5)` → ${latex(pred_ctx)}$",
			f"- Predicate with context: `latex(condition: x > 1.5, ctx)` → ${latex(pred_ctx, LatexCtx(ctx))}$",
			"",
		]
	)

	# NEW SECTION: Show flags functionality
	lines.extend(
		[
			"### Show Flags - Controlling Display Options",
			"",
			"The `latex()` function supports Show flags that control what information is displayed:",
			"",
			"- `Show.VALUES`: Shows variable values as `x:5`",
			"- `Show.WORK`: Shows the evaluation result as `expr → result`",
			"- `Show.VALUES | Show.WORK` (default): Shows both values and result",
			"- `Show(0)`: Shows only structure (no values or work)",
			"",
		]
	)

	# Examples of show_values
	add_show = x_ctx + y_ctx
	comp_show = x_ctx < y_ctx
	complex_show = (x_ctx + z_ctx) * y_ctx

	lines.extend(
		[
			f"- Structure only: `latex(x + y, LatexCtx(ctx, Show(0)))` → ${latex(add_show, LatexCtx(ctx, Show(0)))}$",
			f"- VALUES only: `latex(x + y, LatexCtx(ctx, Show.VALUES))` → ${latex(add_show, LatexCtx(ctx, Show.VALUES))}$",
			f"- WORK only: `latex(x + y, LatexCtx(ctx, Show.WORK))` → ${latex(add_show, LatexCtx(ctx, Show.WORK))}$",
			f"- Both (default): `latex(x + y, LatexCtx(ctx))` → ${latex(add_show, LatexCtx(ctx))}$",
			"",
			"**Boolean Expressions:**",
			f"- Structure: `latex(x < y, LatexCtx(ctx, Show(0)))` → ${latex(comp_show, LatexCtx(ctx, Show(0)))}$",
			f"- VALUES: `latex(x < y, LatexCtx(ctx, Show.VALUES))` → ${latex(comp_show, LatexCtx(ctx, Show.VALUES))}$",
			f"- WORK: `latex(x < y, LatexCtx(ctx, Show.WORK))` → ${latex(comp_show, LatexCtx(ctx, Show.WORK))}$",
			f"- Both: `latex(x < y, LatexCtx(ctx))` → ${latex(comp_show, LatexCtx(ctx))}$",
			"",
			"**Complex Expressions:**",
			f"- Structure: `latex((x + z) * y, LatexCtx(ctx, Show(0)))` → ${latex(complex_show, LatexCtx(ctx, Show(0)))}$",
			f"- VALUES: `latex((x + z) * y, LatexCtx(ctx, Show.VALUES))` → ${latex(complex_show, LatexCtx(ctx, Show.VALUES))}$",
			f"- Both: `latex((x + z) * y, LatexCtx(ctx))` → ${latex(complex_show, LatexCtx(ctx))}$",
			"",
		]
	)

	# Footer
	lines.extend(
		[
			"---",
			"",
			"*Generated by the mahonia LaTeX module test suite*",
			"",
			"To regenerate this file, run: `python -m pytest tests/test_latex_examples.py::test_generate_latex_examples`",
		]
	)

	# Write the markdown file
	output_path = Path(__file__).parent / "latex_examples.md"
	with open(output_path, "w", encoding="utf-8") as f:
		f.write("\n".join(lines))

	print(f"Generated LaTeX examples at {output_path}")


if __name__ == "__main__":
	test_generate_latex_examples()
